# -*- coding: utf-8 -*-
"""BONIFICACION PARCIAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EH-FbX3OdytG4H3QFL2N0ZmrOAh5U0DD
"""



#juego del 21
import random
print("\t \t  \t ***JUGUEMOS 21***")
p1= input("escribe el nombre del primer jugador ")
p2= input("escribe el nombre del segundo jugador ")
decision1= input(f"hola {p1} quieres jugar 21? escribe S(si) o N(no)")
decision2= input(f"hola {p2} quieres jugar 21? escribe S(si) o N(no)")
cartas=(1,2,3,4,5,6,7,8,9,10,11,12)    #tupla de la cual se obtendran los valores de las cartas
juego =input("estan listos? escribe SI o NO")
while juego in ['si', 'sI', 'Si', 'SI']:
  while decision1 in ['S', 's']:
      p1_carta1= random.choice(cartas) 
      p1_carta2=random.choice(cartas)
      p1_carta3=random.choice(cartas)
      total_p1= (p1_carta1+p1_carta2+p1_carta3)
      if (p1_carta3 != p1_carta1) and (p1_carta3 != p1_carta2) and (p1_carta1 != p1_carta2):  #esto asegura que no se repitan cartas
        print(f"{p1} tu juego suma un total de {total_p1}")
      else:
        p1_carta2=random.choice(cartas)
        p1_carta3=random.choice(cartas)
      break
  while decision2 in ['S', 's']:
      p2_carta1= random.choice(cartas)
      p2_carta2=random.choice(cartas)
      p2_carta3=random.choice(cartas)
      total_p2= (p2_carta1+p2_carta2+p2_carta3)
      if (p2_carta3 != p2_carta1) and (p2_carta3 != p2_carta2) and (p2_carta1 != p2_carta2):    #esto asegura que no se repitan cartas
        print(f"{p2} tu juego suma un total de {total_p2}")
      else:
        p1_carta2=random.choice(cartas)
        p1_carta3=random.choice(cartas)
      print(f"{p1} tus cartas son {p1_carta1}, {p1_carta2}, {p1_carta3}")   #Se presenta al usuario su colección de cartas para esta partida
      print(f"{p2} tus cartas son {p2_carta1}, {p2_carta2}, {p2_carta3}")
      if total_p1 > total_p2 and total_p1<21: #se evaluann todos los posibles resultados para poder determinar el ganador
        print(f"\t \t FELICIDADES {p1} HAS GANADO")
      elif total_p2>total_p1 and total_p2<21:
        print(f"\t \t ¡¡FELICIDADES {p2} HAS GANADO!!")
      elif total_p1==total_p2:
        print("lo siento chicos, hay un empate")
      elif (total_p1<total_p2) and (total_p2>21):
        print(f"\t \t FELICIDADES {p1} HAS GANADO")
      elif (total_p2<total_p1) and (total_p1>21):
        print(f"\t \t ¡¡FELICIDADES {p2} HAS GANADO!!")
      elif (total_p1>21) and (total_p2>21):
        print(f"Lo siento amigos, no hay ganador")
      juego= input(f"quieren repetir? ") #si responde afirmativamente, empezará de nuevo el juego
      break
print("\t \t \t ***HEMOS TERMINADO***")